### ISSUE TITLE
Umbrella issue for the Deep Learning notebook

### ISSUE THREAD

**Issue by m09** [mloncode/amld2019-workshop#4]
Please create one issue per bullet point when you start working on them and edit this message to add the link to it.

- [ ] Use PyTorch and PyTorch Lightning
- [ ] Switch to Precision/Recall/F1 (Optionally BLEU and ROUGE also)
- [ ] Add SotA section, highlighting the results from publications and NLP domain
       (size of the dataset, etc) 
- [ ] Use Tree-sitter for preprocessing
- [ ] Include more experiments (ablation study, effect of the dataset size, GGNN model, comparison of structured and non-structured features)
- [ ] Make it simpler (move code to external file, use collapsible cells)
